# Generated by Django 5.0.3 on 2024-05-05 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Investment',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
