# Generated by Django 5.0.3 on 2024-05-05 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='annual_return',
            field=models.DecimalField(decimal_places=2, max_digits=50),
        ),
    ]
