# Generated by Django 5.0.3 on 2024-05-05 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_investment_annual_return'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='image',
            field=models.ImageField(upload_to='static/images'),
        ),
    ]
