# Generated by Django 5.0.3 on 2024-05-05 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_investment_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='image',
        ),
    ]
